output: Node.o LinkedList.o La3.o
	g++ Node.o LinkedList.o La3.o -o output

Node.o: Node.cpp Node.h
	g++ -c Node.cpp

LinkedList.o: LinkedList.cpp LinkedList.h
	g++ -c LinkedList.cpp

La3.o: La3.cpp  
	g++ -c La3.cpp

clean: 
	rm *.o output



